### ISSUE TITLE
Main menu breaks pause menu

### ISSUE THREAD

**Issue by XanderMooney** [ponyfan88/Craigs-Adventure#5]
Loading the game via the main menu breaks the pause menu, probably because of declared variables not being found

**Comment by ponyfan88** [comment]
do variables set in editor not persist through scene changes? these variables are NOT part of any manager that is not destroyed on load (as in, they are all part of gameobjects that should be reset when we click play).

**Comment by ponyfan88** [comment]
i would much more prefer the idea that we do not stop our "ended" state, but since we reload the scene would that even matter?

**Comment by ponyfan88** [comment]
[this](https://answers.unity.com/questions/41891/static-variables-between-scenes.html) seems to confirm my thoughts.
ended and pause are both marked as static (so that scripts can use them without getting the pause script) as such initializing them inside pause.cs does literally nothing once we refresh the scene.

**Comment by ponyfan88** [comment]
this no longer happens as of the latest commit
